#!/usr/bin/env python
import time
import os
import errno

import subprocess

oa_config	= ('OA/getEnclosure.py',	'LoginCSVs/OA.csv')
vc_config	= ('VC/getEnclosure.py',	'LoginCSVs/VC.csv')
p2000_config	= ('P2000/getEnclosure.py',	'LoginCSVs/P2000.csv')
procurve_config	= ('ProCurve/getEnclosure.py',	'LoginCSVs/ProCurve.csv')

def getCall(config, cwd, dir):
	cmd_args = "%s/%s -i %s/%s -o %s" % (cwd, config[0], cwd, config[1], dir)
	#print cmd_args
	if os.path.isfile(config[0]) and os.path.isfile(config[1]):
		subprocess.call(cmd_args.split())
	else:
		print("One of the two files, %s or %s is missing." % (config[0], config[1]))

if __name__ == "__main__":
	cwd = os.path.dirname(os.path.realpath(__file__))
	dir = cwd + '/data_' + time.strftime("%Y-%m-%d")
	try:
		os.makedirs(dir)
	except OSError as exception:
		if exception.errno != errno.EEXIST:
			raise
	
	getCall(oa_config, cwd, dir)
	getCall(vc_config, cwd, dir)
	getCall(p2000_config, cwd, dir)
	getCall(procurve_config, cwd, dir)

