#!/usr/bin/env python

explanation_strings_Tbl = {
'background-scrub'			: 'Shows whether disks in vdisks are automatically checked for disk defects to ensure system health.',
'background-scrub-interval'		: 'Shows the interval in hours between background vdisk scrub finishing and starting again, from 1-360 hours. The default is 24 hours.',
'partner-firmware-upgrade'		: 'Shows whether component firmware versions are monitored and will be automatically updated on the partner controller.',
'utility-priority'			: 'Priority at which data-redundancy utilities, such as vdisk verify and reconstruct, run with respect to I/O operations competing for the system\'s processors.',
'smart'					: 'Shows whether SMART (Self-Monitoring Analysis and Reporting Technology) is enabled or disabled for disks.',
'dynamic-spares'			: 'Shows whether the storage system will automatically use a compatible disk as a spare to replace a failed disk in a vdisk if no compatible spare is available.',
'emp-poll-rate'				: 'Shows the interval in seconds at which the storage system will poll each enclosure\'s Enclosure Management Processor (EMP) for status changes, from 5-3600 seconds. The default is 5 seconds.',
'host-cache-control'			: 'Shows whether hosts are allowed to use the SCSI MODE SELECT command to change the storage system\'s write-back cache setting.',
'sync-cache-mode'			: 'Shows how the SCSI SYNCHRONIZE CACHE command is handled.',
'independent-cache'			: 'Shows the cache redundancy mode for a dual-controller storage system.',
'missing-lun-response'			: 'Shows whether host drivers may probe for LUNs until the host drivers reach the LUN to which they have access.',
'controller-failure'			: 'Shows whether the cache policy will change from write-back to write-through when a controller fails.',
'super-cap-failure'			: 'Shows whether the cache policy will change from write-back to write-through when the super-capacitor that provides backup power for cache is not fully charged or fails.',
'compact-flash-failure'			: 'Shows whether the cache policy will change from write-back to write-through when CompactFlash memory is not detected during POST (Power-On Self-Test), fails during POST, or fails during controller operation.',
'power-supply-failure'			: 'Shows whether the cache policy will change from write-back to write-through when a power supply fails.',
'fan-failure'				: 'Shows whether the cache policy will change from write-back to write-through when a fan fails.',
'temperature-exceeded'			: 'Shows whether the system will shut down a controller when its temperature exceeds the critical operating range.',
'partner-notify'			: 'Shows whether the partner controller will be notified when a trigger condition occurs.',
'auto-write-back'			: 'Shows whether the cache policy will change from write-through to write-back when the trigger condition is cleared.',
'disk-dsd-enable'			: 'Shows whether available disks and global spares will spin down after a period of inactivity shown by the disk-dsd-delay property.',
'disk-dsd-delay'			: 'Specifies the period of inactivity in minutes after which available disks and global spares will spin down.',
'background-disk-scrub'			: 'Shows whether disks that are not in vdisks are automatically checked for disk defects to ensure system health. The interval between background disk scrub finishing and starting again is 72 hours.',
'managed-logs'				: 'Shows whether the managed logs feature is enabled, which allows log files to be transferred from the storage system to a log-collection system to avoid losing diagnostic data as logs fill.',
'single-controller'			: 'For a system that had two controller modules but now has only one and is intended to be used as a single-controller system, this property shows whether the operating/redundancy mode is set to Single Controller. This prevents the system from reporting the absent partner controller as an error condition.',
'drive-write-back-cache'		: 'Disk write-back cache is disabled for all disks in the system and will be enabled for new disks added to the system. This parameter cannot be changed.',
'drive-timeout-retry-max'		: 'Maximum number of times a timed-out I/O operation can be retried before the operation is failed. The default is 3.',
'drive-attempt-timeout'			: 'Number of seconds before an I/O operation is aborted and possibly retried. The default is 8 seconds.',
'drive-overall-timeout'			: 'Total time in seconds before an I/O operation is failed regardless of the drive-attempt-timeout and drive-timeout-retry-max settings. The default is 105 seconds.',
'email-notification'			: 'Shows whether email (SMTP) notification of events is enabled.',
'email-notification-filter'		: 'The minimum severity for which the system should send notifications.',
'email-notify-address-4'		: 'Shows the email address for the log-collection system used by the logmanagement feature.',
'email-server'				: 'The IP address of the SMTP mail server to use for the email messages',
'email-domain'				: 'The domain name that, with the sender name, forms the "from" address for remote notification.',
'email-sender'				: 'The sender name that, with the domain name, forms the "from" address for remote notification.',
'include-logs'				: 'Shows whether system log files will automatically be attached for email notification messages generated by the log-management feature. This is the "push" mode of log management. This option is disabled by default.',
'chap'					: 'Shows whether Challenge-Handshake Authentication Protocol (CHAP) is enabled.',
'jumbo-frames'				: 'Shows whether support for jumbo frames is enabled.',
'isns'					: 'Shows whether support for Internet Storage Name Service (iSNS) is enabled.',
'isns-ip'				: 'Address of the iSNS server. The default address is all zeroes.',
'isns-alt-ip'				: 'Address of the alternate iSNS server. The default address is all zeroes.',
'iscsi-speed'				: 'iSCSI host port link speed.',
'iscsi-ip-version'			: 'iSCSI IP version.',

'durable-id'				: 'Controller network port ID in the form mgmtport_controller-ID.',
'ip-address' 				: 'Controller network port IP address.',
'gateway'				: 'Controller network port gateway IP address',
'subnet-mask'				: 'Controller network port IP subnet mask',
'mac-address'				: 'Controller network port MAC address.',
'addressing-mode'			: 'Manual: Obtain network address from manual (static) settings. DHCP: Use DHCP to obtain network address. This is the default.',
'health'				: 'The health of the network connection.',
'health-reason'				: 'If Health is not OK, the reason for the health state.',
'health-recommendation'			: 'If Health is not OK, the recommended actions to take to resolve the health issue.',

'wbi-http'				: 'The standard SMU web server is disabled/enabled.',
'wbi-https'				: 'The secure SMU web server is disabled/enabled.',
'cli-telnet'				: 'The standard CLI is disabled/enabled.',
'cli-ssh'				: 'The secure shell CLI is disabled/enabled.',
'smis'					: 'The secure SMI-S interface is disabled/enabled.',
'usmis'					: 'The unsecure SMI-S interface is disabled/enabled.',
'ftp'					: 'The FTP interface is disabled/enabled.',
'snmp'					: 'The SNMP interface is disabled/enabled.',
'debug-interface'			: 'The Telnet debug port is disabled/enabled.',
'inband-ses'				: 'The in-band SES interface is disabled/enabled.',
'redundancy-mode'			: 'The system\'s operating mode, also called the cache redundancy mode.',
'snmp-enabled'				: 'Shows whether the Simple Network Management Protocol (SNMP) interface is enabled or disabled.',
'snmp-filter'				: 'Minimum level of events to include for SNMP traps.',
'snmp-read-community'			: 'Community string for SNMP read-only access (not shown to Monitor users). The default is public.',
'snmp-write-community'			: 'Community string for SNMP write access (not shown to Monitor users). The default is private.',

'ulp-enabled'				: 'Shows true to indicate that the system is using Unified LUN Presentation, which can expose all LUNs through all host ports on both controllers.',
'profiles-enabled'			: 'Shows whether host profiles are enabled, which determines whether LUN 0 can be assigned to volume mappings.',

'max-ports'				: 'Number of host-interface ports in the controller enclosure.',
'max-drives'				: 'Number of disks that the system supports.',
'max-volumes'				: 'Number of volumes that the system supports.',
'max-vdisks'				: 'Number of vdisks that the system supports.',
'max-luns'				: 'Number of LUNs that the system supports.',
'max-owned-arrays-per-controller'	: 'Number of vdisks that each controller supports.',

'max-capi-arrays'			: 'Same as max-vdisks.',
'max-chunk-size'			: 'Maximum chunk size for vdisks: 64 KB.',
'min-chunk-size'			: 'Minimum chunk size for vdisks: 16 KB.',
'physical-position-offset'		: 'Starting index for physical components (enclosures, disks, etc.) in the storage system.',
'backoff-percentage'			: 'Percentage of disk capacity that is reserved to compensate for minor capacity differences between disk drives so they can be used interchangeably. This is not settable by users. The default is 1 percent.',
'metadata-size'				: 'Amount of metadata, in blocks, stored on each disk.',
'local-controller'			: 'Controller you are currently logged in to - Controller A/Controller B.',
'serial-number'				: 'Last five digits of the midplane serial number.',
'ip-address-mode'			: 'CAPI_TWO_IP_ADDRESSES_MODE or CAPI_ONE_IP_ADDRESS_MODE.',
'debug-flags'				: 'For use by service personnel.',
'enclosure-flags'			: 'For internal use only.',
'num-globalspares'			: 'Number of global-spare disks defined in the storage system.',
'dynamic-spare-rescan-rate'		: 'Interval at which the system is scanned for disks automatically designated as spares, if the dynamic spares feature is enabled.',
'performance-tuning-flags'		: 'For internal use only.',
'min-backing-store-size'		: 'Minimum snap-pool size in blocks.',

'username'				: 'User name.',
'roles'					: 'monitor: View-only access to selected user interfaces. This is the default. manage: Modify access to selected user interfaces.',
'user-type'				: 'The user\'s level of technical expertise: Novice, Standard, Advanced, or Diagnostic. All user types have access to all commands. The default is Standard.',
'user-locale'				: 'Display language for this user. The default is English.',
'interface-access-WBI'			: 'User can use the web-browser interface (SMU). Values - "x" or (blank).',
'interface-access-CLI'			: 'User can use the command-line interface. Values - "x" or (blank).',
'interface-access-FTP'			: 'User can use the file transfer protocol interface. Values - "x" or (blank).',
'interface-access-SMIS'			: 'User can use the Storage Management Initiative Specification (SMI-S) interface. Values - "x" or (blank).',
'interface-access-SNMP'			: 'User can use the SNMPv3 interface. Values - "U" or "T" or (blank).',
'storage-size-base'			: 'The base for entry and display of storage-space sizes. Values - 2 or 10',
'storage-size-precision'		: 'The number of decimal places (1-10) for display of storage-space sizes. The default is 1.',
'storage-size-units'			: 'The unit for display of storage-space sizes.',
'timeout'				: 'Time in seconds that the session can be idle before it automatically ends. Valid values are 120-43200 seconds (2-720 minutes). The default is 1800 seconds (30 minutes).',
'ui-refresh'				: 'User-interface refresh rate, which is 30 seconds.',
'authentication-type'			: 'For an SNMPv3 user, this specifies whether to use a security authentication protocol. Authentication uses the user password.',
'privacy-type'				: 'For an SNMPv3 user, this specifies whether to use a security encryption protocol.',
'password'				: 'User password. For a standard user the password is represented by eight asterisks. For an SNMPv3 user this is the authentication password; it is shown in clear text for reference when configuring users in the corresponding management application.',
'privacy-password'			: 'Encryption password for an SNMPv3 user whose privacy type is set to DES or AES. The password is shown in clear text for reference when configuring users in the corresponding management application.',
'trap-destination'			: 'For an SNMPv3 user whose interface-access-SNMP property is set to snmptarget, this specifies the IP address of the host that will receive SNMP traps.',
'sc-cpu-type'				: 'Storage Controller processor type.',
'bundle-version'			: 'Firmware bundle version.',
'build-date'				: 'Firmware bundle build date.',
'sc-fw'					: 'Storage Controller firmware version.',
'sc-baselevel' 				: 'Storage Controller firmware base level.',
'sc-memory'				: 'Storage Controller memory-controller FPGA firmware version.',
'sc-loader'				: 'Storage Controller loader firmware version.',
'capi-version'				: 'Configuration API (CAPI) version.',
'mc-fw string'				: 'Management Controller firmware version.',
'mc-loader'				: 'Management Controller loader firmware version.',
'ec-fw'					: 'Expander Controller firmware version.',
'pld-rev'				: 'Complex Programmable Logic Device (CPLD) firmware version.',
'hw-rev'				: 'Controller hardware version.',
'him-rev'				: 'Host interface module revision.',
'him-model'				: 'Host interface module model.',
'backplane-type'			: 'Backplane type.',
'host-channel_revision'			: 'Host interface hardware (chip) version.',
'disk-channel_revision'			: 'Disk interface hardware (chip) version.',
'mrc-version'				: 'Memory Reference Code (MRC) version for Storage Controller boot Flash.'
}
